### PR TITLE
Fix Android build script

### PR DESCRIPTION
**Pull request by davidshen84**
- I fixed build script for OpenSSL and curl
- I cannot reproduce your issue with protobuf

```
protoc --version
libprotoc 3.1.0

which protoc
/usr/local/bin/protoc
```

I install my protoc from brew. I hope this can help you troubleshoot the issue on your side.

### CODE REVIEW

**Comment by leenjewel** [comment]
I think `$pwd_path` is better than `pwd`, `pwd` is work dir may not script file absolute path

These codes return script file absolute path
```
SOURCE="$0"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
pwd_path="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
```

iOS static library build output to `tools/../output/ios/xxxxx` ,so I hope Android static library build output to `tools/../output/android/xxxxx`, we could zip `output` file folder and release it

**Comment by davidshen84** [comment]
- I think you need [this](http://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/). But allowing the script to execute from another directory is complicate. Needs more time to test it.

- OK, I will move android output to **../output/android/$abi**

**Comment by leenjewel** [comment]
- OK, keep use `pwd`, do not change

- Thanks again 👍

**Comment by leenjewel** [comment]
Oh by the way

I have released a version yesterday

Now our output file folder like:

iOS

<center>
openssl-curl-ios-output
</center>

Android

<center>
openssl-curl-ios-output
</center>

**Comment by leenjewel** [comment]
Thank you for your job 👍

**Comment by davidshen84** [comment]
Are you sure you want path like `android/curl-android-x86`? I prefer path like `android/curl-x86`.

You can simply copy everything under the `android` directory into an Android project, and you don't need an *android* label inside an Android project to remind you.

**Comment by leenjewel** [comment]
Your suggestion is better, `android/curl-{ABI}` is better, I will change iOS output name like `ios/curl-{ARCH}`

**Pull request merged**
